version: '2'

services:

  ####################################
  #  LOGIC MODULE ON DC 1            #
  ####################################
  lmpostgres1:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  logicmodule1:
    image: "bscdataclay/logicmodule"
    ports:
      - "11034:1034"
    env_file:
      - ./env/dc1/LM.environment
      - ./env/PG.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=lmpostgres1
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

  ####################################
  #  JAVA DATA SERVICES ON DC 1      #
  ####################################
  ds1postgres1:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  ds1java1:
    image: "bscdataclay/dsjava"
    ports:
      - 2127
    env_file:
      - ./env/PG.environment
      - ./env/dc1/DS1.environment
      - ./env/dc1/LM.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres1
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

  ds2postgres1:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  ds2java1:
    image: "bscdataclay/dsjava"
    ports:
      - 2128
    env_file:
      - ./env/PG.environment
      - ./env/dc1/DS2.environment
      - ./env/dc1/LM.environment
    environment:
      - DATASERVICE_NAME=DS2
      - POSTGRES_HOST=ds2postgres1
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

  ####################################
  #  PYTHON DATA SERVICES ON DC 1    #
  ####################################

  # Python ExecutionEnvironment (which, by default, are unused)
  # See initDC.sh shell script for more information on initialization
  ds1pythonee1:
    image: "bscdataclay/dspython"
    ports:
      - 6867
    env_file:
      - ./env/dc1/LM.environment
      - ./env/dc1/DS1.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres1
      - DEBUG=false
      #- PYTHONVERBOSE=1



  #############################################
  #   LOGIC MODULE ON DC 2                    #
  #############################################
  lmpostgres2:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  logicmodule2:
    image: "bscdataclay/logicmodule"
    ports:
      - "12034:2034"
    env_file:
      - ./env/dc2/LM.environment
      - ./env/PG.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=lmpostgres2
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

  ####################################
  #    JAVA DATA SERVICES ON DC 2    #
  ####################################
  ds1postgres2:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  ds1java2:
    image: "bscdataclay/dsjava"
    ports:
      - 3127
    env_file:
      - ./env/PG.environment
      - ./env/dc2/DS1.environment
      - ./env/dc2/LM.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres2
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

  ####################################
  #  PYTHON DATA SERVICES ON DC 2    #
  ####################################

  # Python ExecutionEnvironment (which, by default, are unused)
  # See initDC.sh shell script for more information on initialization
  ds1pythonee2:
    image: "bscdataclay/dspython"
    ports:
      - 6867
    env_file:
      - ./env/dc2/LM.environment
      - ./env/dc2/DS1.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres2
      - DEBUG=false
      #- PYTHONVERBOSE=1



  ####################################
  #  LOGIC MODULE FOR BACKUP         #
  ####################################
  lmpostgres_bk:
    image: postgres:9.5.12
    env_file:
      - ./env/PG.environment
    command: -c fsync=off

  logicmodule_bk:
    image: "bscdataclay/logicmodule"
    ports:
      - "13034:3034"
    env_file:
      - ./env/dc1/LM_BK.environment
      - ./env/PG.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=lmpostgres_bk
    volumes:
      - ./prop/global.properties:/usr/src/app/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/app/log4j2.xml:ro

